import type { Banner, Branch, Category, DealPamphlet, Product } from "@dismart/shared";

export const BRANCHES: Branch[] = [
  {
    id: "branch-meyerton",
    name: "Meyerton",
    location: "Meyerton",
    address: "12 Kerk Street, Meyerton, 1961",
    whatsapp_number: "27821234567",
    phone: "0161234567",
    is_active: true,
    lat: -26.5597,
    lng: 27.9994,
  },
  {
    id: "branch-riversdale",
    name: "Riversdale",
    location: "Riversdale",
    address: "5 Main Road, Riversdale, 6670",
    whatsapp_number: "27827654321",
    phone: "0287654321",
    is_active: true,
    lat: -34.0944,
    lng: 21.2586,
  },
  {
    id: "branch-vanderbijlpark",
    name: "Vanderbijlpark",
    location: "Vanderbijlpark",
    address: "88 Frikkie Meyer Blvd, Vanderbijlpark, 1911",
    whatsapp_number: "27829876543",
    phone: "0169876543",
    is_active: true,
    lat: -26.7005,
    lng: 27.8378,
  },
];

export const CATEGORIES: Category[] = [
  { id: "cat-groceries", name: "Groceries", icon_name: "ShoppingBasket", sort_order: 1 },
  { id: "cat-household", name: "Household", icon_name: "Home", sort_order: 2 },
  { id: "cat-cleaning", name: "Cleaning", icon_name: "Sparkles", sort_order: 3 },
  { id: "cat-personal-care", name: "Personal Care", icon_name: "HeartPulse", sort_order: 4 },
  { id: "cat-toiletries", name: "Toiletries", icon_name: "Bath", sort_order: 5 },
  { id: "cat-baby", name: "Baby & Toddler", icon_name: "Baby", sort_order: 6 },
  { id: "cat-confectionery", name: "Confectionery", icon_name: "Cookie", sort_order: 7 },
  { id: "cat-beverages", name: "Beverages", icon_name: "Coffee", sort_order: 8 },
  { id: "cat-electronics", name: "Electronics", icon_name: "Smartphone", sort_order: 9 },
  { id: "cat-appliances", name: "Appliances", icon_name: "Plug", sort_order: 10 },
  { id: "cat-clothing", name: "Clothing", icon_name: "Shirt", sort_order: 11 },
  { id: "cat-toys", name: "Toys", icon_name: "Gamepad2", sort_order: 12 },
  { id: "cat-hardware", name: "Hardware", icon_name: "Wrench", sort_order: 13 },
  { id: "cat-stationery", name: "Stationery", icon_name: "Pencil", sort_order: 14 },
];

export const PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "Jungle Oats 1kg",
    description: "Classic rolled oats, a South African breakfast staple.",
    price: 39.99,
    category_id: "cat-groceries",
    image_url: "https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=400&h=400&fit=crop",
    expiry_date: "2025-12-01",
    is_special: true,
    stock_status: "in_stock",
    created_at: "2026-01-01T00:00:00Z",
    branch_ids: ["branch-meyerton", "branch-vanderbijlpark", "branch-riversdale"],
  },
  {
    id: "prod-2",
    name: "Lucky Star Pilchards 400g",
    description: "Pilchards in tomato sauce, tinned.",
    price: 24.99,
    category_id: "cat-groceries",
    image_url: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=400&h=400&fit=crop",
    expiry_date: "2026-06-01",
    is_special: false,
    stock_status: "in_stock",
    created_at: "2026-01-01T00:00:00Z",
    branch_ids: ["branch-meyerton", "branch-vanderbijlpark", "branch-riversdale"],
  },
  {
    id: "prod-3",
    name: "All Gold Tomato Sauce 700ml",
    description: "South Africa's favourite tomato sauce.",
    price: 34.99,
    category_id: "cat-groceries",
    image_url: "https://images.unsplash.com/photo-1472476443507-c7a5948772fc?w=400&h=400&fit=crop",
    expiry_date: "2026-09-01",
    is_special: true,
    stock_status: "in_stock",
    created_at: "2026-01-01T00:00:00Z",
    branch_ids: ["branch-meyerton", "branch-riversdale"],
  },
  {
    id: "prod-4",
    name: "Glad Large Bin Bags 20 Pack",
    description: "Heavy duty black bin bags for large waste bins.",
    price: 49.99,
    category_id: "cat-household",
    image_url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop",
    expiry_date: null,
    is_special: true,
    stock_status: "in_stock",
    created_at: "2026-01-01T00:00:00Z",
    branch_ids: ["branch-meyerton", "branch-vanderbijlpark", "branch-riversdale"],
  },
  {
    id: "prod-5",
    name: "Aerolite Food Storage Set 5pc",
    description: "Stackable airtight food storage containers.",
    price: 89.99,
    category_id: "cat-household",
    image_url: "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=400&h=400&fit=crop",
    expiry_date: null,
    is_special: false,
    stock_status: "in_stock",
    created_at: "2026-01-01T00:00:00Z",
    branch_ids: ["branch-meyerton", "branch-vanderbijlpark"],
  },
  {
    id: "prod-6",
    name: "Handy Andy Multi-Purpose 750ml",
    description: "Cream cleaner for all household surfaces.",
    price: 29.99,
    category_id: "cat-cleaning",
    image_url: "https://images.unsplash.com/photo-1585586723682-168e3b2a9370?w=400&h=400&fit=crop",
    expiry_date: null,
    is_special: true,
    stock_status: "in_stock",
    created_at: "2026-01-01T00:00:00Z",
    branch_ids: ["branch-meyerton", "branch-vanderbijlpark", "branch-riversdale"],
  },
  {
    id: "prod-7",
    name: "Sunlight Dishwashing Liquid 750ml",
    description: "Lemon-scented dishwashing liquid, tough on grease.",
    price: 22.99,
    category_id: "cat-cleaning",
    image_url: "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&h=400&fit=crop",
    expiry_date: null,
    is_special: false,
    stock_status: "in_stock",
    created_at: "2026-01-01T00:00:00Z",
    branch_ids: ["branch-meyerton", "branch-riversdale"],
  },
  {
    id: "prod-8",
    name: "Dove Body Wash 400ml",
    description: "Moisturising body wash with 1/4 moisturising cream.",
    price: 59.99,
    category_id: "cat-personal-care",
    image_url: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400&h=400&fit=crop",
    expiry_date: null,
    is_special: true,
    stock_status: "in_stock",
    created_at: "2026-01-01T00:00:00Z",
    branch_ids: ["branch-meyerton", "branch-vanderbijlpark", "branch-riversdale"],
  },
  {
    id: "prod-9",
    name: "Nivea Men Roll-On 50ml",
    description: "48h protection anti-perspirant deodorant.",
    price: 44.99,
    category_id: "cat-personal-care",
    image_url: "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=400&h=400&fit=crop",
    expiry_date: null,
    is_special: false,
    stock_status: "in_stock",
    created_at: "2026-01-01T00:00:00Z",
    branch_ids: ["branch-meyerton", "branch-vanderbijlpark"],
  },
  {
    id: "prod-10",
    name: "Colgate Triple Action 100ml",
    description: "Triple action cavity protection toothpaste.",
    price: 27.99,
    category_id: "cat-toiletries",
    image_url: "https://images.unsplash.com/photo-1559589689-577eca9d670f?w=400&h=400&fit=crop",
    expiry_date: null,
    is_special: true,
    stock_status: "in_stock",
    created_at: "2026-01-01T00:00:00Z",
    branch_ids: ["branch-meyerton", "branch-vanderbijlpark", "branch-riversdale"],
  },
  {
    id: "prod-11",
    name: "Listerine Coolmint 500ml",
    description: "Antibacterial mouthwash for lasting fresh breath.",
    price: 54.99,
    category_id: "cat-toiletries",
    image_url: "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=400&h=400&fit=crop",
    expiry_date: null,
    is_special: false,
    stock_status: "low_stock",
    created_at: "2026-01-01T00:00:00Z",
    branch_ids: ["branch-meyerton"],
  },
  {
    id: "prod-12",
    name: "Pampers Active Baby Size 3 52pk",
    description: "Up to 12 hours of dryness for active babies.",
    price: 149.99,
    category_id: "cat-baby",
    image_url: "https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=400&h=400&fit=crop",
    expiry_date: null,
    is_special: true,
    stock_status: "in_stock",
    created_at: "2026-01-01T00:00:00Z",
    branch_ids: ["branch-meyerton", "branch-vanderbijlpark", "branch-riversdale"],
  },
  {
    id: "prod-13",
    name: "Beacon Assorted Chocolates 200g",
    description: "A selection of South African favourite chocolates.",
    price: 34.99,
    category_id: "cat-confectionery",
    image_url: "https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=400&h=400&fit=crop",
    expiry_date: "2026-03-01",
    is_special: true,
    stock_status: "in_stock",
    created_at: "2026-01-01T00:00:00Z",
    branch_ids: ["branch-meyerton", "branch-vanderbijlpark", "branch-riversdale"],
  },
  {
    id: "prod-14",
    name: "Simba Chips Variety 6 Pack",
    description: "Mixed flavour Simba chips snack pack.",
    price: 44.99,
    category_id: "cat-confectionery",
    image_url: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400&h=400&fit=crop",
    expiry_date: "2026-04-01",
    is_special: false,
    stock_status: "in_stock",
    created_at: "2026-01-01T00:00:00Z",
    branch_ids: ["branch-meyerton", "branch-riversdale"],
  },
  {
    id: "prod-15",
    name: "Coke 2L",
    description: "Coca-Cola Original Taste, 2 litre bottle.",
    price: 22.99,
    category_id: "cat-beverages",
    image_url: "https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400&h=400&fit=crop",
    expiry_date: "2026-05-01",
    is_special: true,
    stock_status: "in_stock",
    created_at: "2026-01-01T00:00:00Z",
    branch_ids: ["branch-meyerton", "branch-vanderbijlpark", "branch-riversdale"],
  },
  {
    id: "prod-16",
    name: "Ricoffy 750g",
    description: "South Africa's favourite chicory coffee blend.",
    price: 79.99,
    category_id: "cat-beverages",
    image_url: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&h=400&fit=crop",
    expiry_date: "2027-01-01",
    is_special: false,
    stock_status: "in_stock",
    created_at: "2026-01-01T00:00:00Z",
    branch_ids: ["branch-meyerton", "branch-vanderbijlpark"],
  },
  {
    id: "prod-17",
    name: "Samsung USB-C Charging Cable 1.5m",
    description: "Fast charging USB-C cable, compatible with most Android devices.",
    price: 99.99,
    category_id: "cat-electronics",
    image_url: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=400&h=400&fit=crop",
    expiry_date: null,
    is_special: true,
    stock_status: "in_stock",
    created_at: "2026-01-01T00:00:00Z",
    branch_ids: ["branch-meyerton", "branch-vanderbijlpark", "branch-riversdale"],
  },
  {
    id: "prod-18",
    name: "Generic Earphones 3.5mm",
    description: "In-ear earphones with built-in microphone.",
    price: 79.99,
    category_id: "cat-electronics",
    image_url: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop",
    expiry_date: null,
    is_special: false,
    stock_status: "low_stock",
    created_at: "2026-01-01T00:00:00Z",
    branch_ids: ["branch-meyerton"],
  },
  {
    id: "prod-19",
    name: "Russell Hobbs Kettle 1.7L",
    description: "Stainless steel cordless electric kettle.",
    price: 349.99,
    category_id: "cat-appliances",
    image_url: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop",
    expiry_date: null,
    is_special: true,
    stock_status: "in_stock",
    created_at: "2026-01-01T00:00:00Z",
    branch_ids: ["branch-meyerton", "branch-vanderbijlpark", "branch-riversdale"],
  },
  {
    id: "prod-20",
    name: "Plain Cotton T-Shirt (Assorted) L",
    description: "100% cotton crew-neck t-shirt, available in assorted colours.",
    price: 59.99,
    category_id: "cat-clothing",
    image_url: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=400&fit=crop",
    expiry_date: null,
    is_special: false,
    stock_status: "in_stock",
    created_at: "2026-01-01T00:00:00Z",
    branch_ids: ["branch-meyerton", "branch-vanderbijlpark"],
  },
  {
    id: "prod-21",
    name: "Foam Football Set",
    description: "Soft foam football, safe for indoor play.",
    price: 49.99,
    category_id: "cat-toys",
    image_url: "https://images.unsplash.com/photo-1575361204480-aadea25e6e68?w=400&h=400&fit=crop",
    expiry_date: null,
    is_special: true,
    stock_status: "in_stock",
    created_at: "2026-01-01T00:00:00Z",
    branch_ids: ["branch-meyerton", "branch-vanderbijlpark", "branch-riversdale"],
  },
  {
    id: "prod-22",
    name: "Stanley Tape Measure 5m",
    description: "Classic yellow Stanley tape measure with metric and imperial.",
    price: 89.99,
    category_id: "cat-hardware",
    image_url: "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=400&h=400&fit=crop",
    expiry_date: null,
    is_special: false,
    stock_status: "in_stock",
    created_at: "2026-01-01T00:00:00Z",
    branch_ids: ["branch-meyerton", "branch-vanderbijlpark"],
  },
  {
    id: "prod-23",
    name: "Croxley A4 Writing Pad 100 Sheets",
    description: "Ruled writing pad, 100 pages, ideal for school or office.",
    price: 29.99,
    category_id: "cat-stationery",
    image_url: "https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=400&h=400&fit=crop",
    expiry_date: null,
    is_special: true,
    stock_status: "in_stock",
    created_at: "2026-01-01T00:00:00Z",
    branch_ids: ["branch-meyerton", "branch-vanderbijlpark", "branch-riversdale"],
  },
];

export const BANNERS: Banner[] = [
  {
    id: "banner-1",
    branch_id: "branch-meyerton",
    image_url: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=1200&h=400&fit=crop",
    headline: "MASSIVE SAVINGS THIS WEEK",
    subtext: "New stock just landed. Grab it before it's gone!",
    link_type: "none",
    link_id: null,
    is_active: true,
    sort_order: 1,
    bg_color: "#1B2B5B",
  },
  {
    id: "banner-2",
    branch_id: "branch-meyerton",
    image_url: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&h=400&fit=crop",
    headline: "HOUSEHOLD ESSENTIALS",
    subtext: "Stock up and save big on everyday must-haves.",
    link_type: "category",
    link_id: "cat-household",
    is_active: true,
    sort_order: 2,
    bg_color: "#E8212A",
  },
  {
    id: "banner-3",
    branch_id: "branch-riversdale",
    image_url: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=1200&h=400&fit=crop",
    headline: "RIVERSDALE SPECIALS",
    subtext: "Exclusive deals at your local Dismart.",
    link_type: "none",
    link_id: null,
    is_active: true,
    sort_order: 1,
    bg_color: "#1B2B5B",
  },
  {
    id: "banner-4",
    branch_id: "branch-vanderbijlpark",
    image_url: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&h=400&fit=crop",
    headline: "VDP BIG DEALS",
    subtext: "Vanderbijlpark's best bargains in one place.",
    link_type: "none",
    link_id: null,
    is_active: true,
    sort_order: 1,
    bg_color: "#E8212A",
  },
];

export const DEAL_PAMPHLETS: DealPamphlet[] = [
  {
    id: "deal-meyerton-weekly",
    branch_id: "branch-meyerton",
    title: "Weekly Savings Pamphlet",
    description: "Browse this week's featured deals before visiting store.",
    asset_url: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=1400&h=900&fit=crop",
    asset_type: "image",
    source: "image_url",
    thumbnail_url: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&h=500&fit=crop",
    is_active: true,
    starts_at: "2026-05-04T00:00:00Z",
    ends_at: null,
    sort_order: 1,
  },
  {
    id: "deal-meyerton-facebook",
    branch_id: "branch-meyerton",
    title: "Facebook Deals Post",
    description: "Open the latest social post with in-store specials.",
    asset_url: "https://www.facebook.com/Dismart",
    asset_type: "external_url",
    source: "facebook_url",
    thumbnail_url: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=500&fit=crop",
    is_active: true,
    starts_at: null,
    ends_at: null,
    sort_order: 2,
  },
];

export function getProductsByBranch(branchId: string): Product[] {
  return PRODUCTS.filter((p) => p.branch_ids.includes(branchId));
}

export function getSpecialsByBranch(branchId: string): Product[] {
  return PRODUCTS.filter((p) => p.branch_ids.includes(branchId) && p.is_special);
}

export function getProductsByCategory(branchId: string, categoryId: string): Product[] {
  return PRODUCTS.filter(
    (p) => p.branch_ids.includes(branchId) && p.category_id === categoryId
  );
}

export function getBannersByBranch(branchId: string): Banner[] {
  return BANNERS.filter((b) => b.branch_id === branchId && b.is_active).sort(
    (a, b) => a.sort_order - b.sort_order
  );
}

export function getDealsByBranch(branchId: string): DealPamphlet[] {
  return DEAL_PAMPHLETS.filter((deal) => deal.branch_id === branchId && deal.is_active).sort(
    (a, b) => a.sort_order - b.sort_order
  );
}

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export function getCategoryById(id: string): Category | undefined {
  return CATEGORIES.find((c) => c.id === id);
}

export function getBranchById(id: string): Branch | undefined {
  return BRANCHES.find((b) => b.id === id);
}

